"""Add game_user Association Table

Revision ID: ad4ac83fd0cb
Revises: 7478260027b8
Create Date: 2024-09-15 22:06:37.081857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4ac83fd0cb'
down_revision = '7478260027b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
